### ISSUE TITLE
can I beg you to share me a VM Snapshot of BINSEC tutorial @ SSPREW-7?

### ISSUE THREAD

**Issue by APlus123** [rbonichon/rbonichon.github.io#1]
Dear Mr. Bonichon, I am a graduate Student who is very interested in your BB-DSE framework. Unfortunately, when I see this page, the link(https://rbonichon.github.io/posts/ssprew-17/) has expired ,so can I beg you to share me a VM Snapshot of BINSEC tutorial @ SSPREW-7?  Much appraciated to you !
My email is : aplus18688@gmail.com

**Comment by rbonichon** [comment]
@APlus123 I will reactivate you the download link tomorrow: it will be available for 2 weeks.

You should note that this VM contains an unreleased development version of BINSEC that was made available for the tutorial at SSPREW.

- it does not contain PINSEC, the PIN based tracer used for concretization in the DSE of BINSEC
- it does not contain IDASEC
- there is no source code
- I can not spend too much time answering questions about it.

The md5 of the new image is `4e05dfb82756b59bf2eb966bed11af88`

**Comment by APlus123** [comment]
@rbonichon Much appraciated to your kind reply, I have downloaded the ova file, and I will compile the non-beta release of BINSEC 20170301. Look forward to your  v0.2 version  on Github!
